# Generated by Django 4.0.4 on 2022-06-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signupin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeroTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('create_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
