# Generated by Django 4.0.4 on 2022-06-17 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signupin', '0003_alter_merotime_create_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='merotime',
            name='create_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
